Repository CSCD488-Team5/SeniorProject, pull requests merged in 2025-05, with the labels that each got.

#48 Notis
  src/frontend/src/components/EventCard.vue
  src/frontend/src/components/ProfileDropdown.vue
  src/main/java/com/Team5/SeniorProject/controller/EventController.java
  src/main/java/com/Team5/SeniorProject/controller/JoinEventController.java
  src/main/java/com/Team5/SeniorProject/service/EmailService.java
  src/main/java/com/Team5/SeniorProject/service/EventService.java
Labels: Make it KOSHER!!!!

#49 Admin role protection for /event/delete
  src/main/java/com/Team5/SeniorProject/controller/EventController.java
  src/main/java/com/Team5/SeniorProject/model/Role.java
  src/main/java/com/Team5/SeniorProject/model/User.java
  src/main/java/com/Team5/SeniorProject/model/UserInitializer.java
  src/main/java/com/Team5/SeniorProject/security/CustomUserDetailsService.java
  src/main/java/com/Team5/SeniorProject/security/SecurityConfig.java
  src/main/java/com/Team5/SeniorProject/security/SecurityService.java
  src/main/java/com/Team5/SeniorProject/service/UserService.java
Labels: enhancement

#55 DeletedPostComments
  src/frontend/src/components/EventDetails.vue
  src/main/java/com/Team5/SeniorProject/controller/CommentController.java
  src/main/java/com/Team5/SeniorProject/model/Event.java
  src/main/java/com/Team5/SeniorProject/model/PostComments.java
  src/main/java/com/Team5/SeniorProject/repository/CommentRepository.java
Labels: enhancement, Make it KOSHER!!!!
